plugin_name: "ShadowRunes"
plugin_commands: "§7[§bShadowRunes§7] §r» "
# Toutes les valeurs sont en "%".
runes:
  damage:
    lore: "§r» Bonus de dégâts : "
    max-multiplier: 20
  vitesse:
    lore: "§r» Bonus de vitesse : "
    max-multiplier: 10